var sum = 3 + 2
console.log(sum)
/*5*/


typeof(3)
console.log(typeof(3))
/*Number*/


typeof(3)===typeof("3")
console.log(typeof(3)===typeof("3"))
/*false*/


x=5/0
console.log(x)
/*Infinity*/

x=3/"bob"
console.log(x)
/*NaN*/

NaN===NaN
console.log(NaN===NaN)
/*false*/

typeof(NaN)
console.log(typeof(NaN))
/*number*/

var hello
console.log(hello)
/*undefined*/

x="some"+"person"
console.log(x)
/*someperson*/

var sport;
sport===undefined
console.log(sport)
/*undefined*/





