/*Construye un codigo bajo las siguientes reglas*/
/*Itera arreglo= [1,4,6,10,22,55,46,2,5,0] utilizando un ciclo for*/
/*Imprime en consola los valores que sean mayores 3*/


var arreglo = [1,4,6,10,22,55,46,2,5,0]

for( var i = 0; i < arreglo. length; i++){
    if(i >3){
        console.log(arreglo[i])
    }
  
}


/*Construye un código bajo las siguientes reglas*/

var arreglo=[]
var i = 0
while(i<5){
    arreglo [i]= i 
    i++
}
console.log(arreglo)

/*Declara un arreglo vacío, con un ciclo while que se ejecute 5 veces , agrega los elementos array*/

var arreglo=[]
var index= 0
while (index<=4){
    console.log ("Elemento No.:",index)
    index++
}

/*Nota : recuerda incrementar la variable contador para que pueda incrementar el cliclo*/


//iterar un arreglo 
var arreglo=['hola',1,true,null]

for(var i=0; i< arreglo.length; i++){
    console.log([i])
}