/*area_de_circulo.JS*/
var radio= 5.3;
var area=Math.PI*radio**2;
console.log(area);
/*respuesta 88.2473*/



/*area_de_rombo.JS*/
var D="8"
var d=6
var area=D+d/2
console.log(area)
/*83*/

/*multiplicacion*/

var dato= prompt("ingresa un numero")
var operacion=dato*2
console. log (operacion)

/*resta*/

var dato1,dato2,num1,num2;
dato1=prompt("Introduce primer numero");
num1=parseInt(dato1);
dato2=prompt("Introduce segundo numero");
num2=parseInt(dato2);
var resultado=num1-num2;
console.log(resultado)
